config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'health_regions#index'

  resources :health_regions
  get 'import_data_api', to: 'health_regions#import_data_api'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/health_region.rb
class HealthRegion < ApplicationRecord
  def self.to_csv
  attributes = %w{dimension british_columbia ha_total ha_1_interior ha_2_fraser ha_3_vancouver_coastal ha_4_vancouver_island ha_5_northern}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

  def self.save_health_region_data(records)
    self.transaction do
      health_region = []
      records.each do |record|
        health_region << self.new(dimension: record["Dimension"] , british_columbia: record["British Columbia"] , 
          ha_total: record["HA Total"] , ha_1_interior: record["HA 1 Interior"] , 
          ha_2_fraser: record["HA 2 Fraser"] , ha_3_vancouver_coastal: record["HA 3 Vancouver Coastal"], 
          ha_4_vancouver_island: record["HA 4 Vancouver Island"], ha_5_northern: record["HA 5 Northern"])
      end
      self.import health_region
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/health_regions_controller.rb
class HealthRegionsController < ApplicationController
  before_action :set_health_region, only: [:show, :edit, :update, :destroy]

  # GET /health_regions
  # GET /health_regions.json
  def index
    @health_regions = HealthRegion.all
    respond_to do |format|
      format.html
      format.csv { send_data @health_regions.to_csv, filename: "health_regions-#{Date.today}.csv" }
    end
  end

  # GET /health_regions/1
  # GET /health_regions/1.json
  def show
  end

  # GET /health_regions/new
  def new
    @health_region = HealthRegion.new
  end

  # GET /health_regions/1/edit
  def edit
  end

  # POST /health_regions
  # POST /health_regions.json
  def create
    @health_region = HealthRegion.new(health_region_params)

    respond_to do |format|
      if @health_region.save
        format.html { redirect_to @health_region, notice: 'Health region was successfully created.' }
        format.json { render :show, status: :created, location: @health_region }
      else
        format.html { render :new }
        format.json { render json: @health_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /health_regions/1
  # PATCH/PUT /health_regions/1.json
  def update
    respond_to do |format|
      if @health_region.update(health_region_params)
        format.html { redirect_to @health_region, notice: 'Health region was successfully updated.' }
        format.json { render :show, status: :ok, location: @health_region }
      else
        format.html { render :edit }
        format.json { render json: @health_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /health_regions/1
  # DELETE /health_regions/1.json
  def destroy
    @health_region.destroy
    respond_to do |format|
      format.html { redirect_to health_regions_url, notice: 'Health region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import_data_api
    find_offset = HealthRegion.count.to_s
    res = GetHealthRegionDataService.get_health_region_data(find_offset, params[:limit])
    if res.present?
      HealthRegion.save_health_region_data(res)
      redirect_to health_regions_path, notice: 'Health region was imported successfully.'
    else
      redirect_to health_regions_path, notice: 'Please try again.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health_region
      @health_region = HealthRegion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def health_region_params
      params.require(:health_region).permit(:dimension, :british_columbia, :ha_total, :ha_1_interior, :ha_2_fraser, :ha_3_vancouver_coastal, :ha_4_vancouver_island, :ha_5_northern)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/health_regions_helper.rb
module HealthRegionsHelper
end

app/views/health_regions/_form.html.erb
<%= form_for(health_region) do |f| %>
  <% if health_region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(health_region.errors.count, "error") %> prohibited this health_region from being saved:</h2>

      <ul>
      <% health_region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :dimension %><br>
    <%= f.text_field :dimension %>
  </p>
  <p>
    <%= f.label :british_columbia %><br>
    <%= f.text_field :british_columbia %>    
  </p>
  <p>
    <%= f.label :ha_total %><br>
    <%= f.text_field :ha_total %>    
  </p>
  <p>
    <%= f.label :ha_1_interior %><br>
    <%= f.text_field :ha_1_interior %>    
  </p>
  <p>
    <%= f.label :ha_2_fraser %><br>
    <%= f.text_field :ha_2_fraser %>    
  </p>
  <p>
    <%= f.label :ha_3_vancouver_coastal %><br>
    <%= f.text_field :ha_3_vancouver_coastal %>    
  </p>
  <p>
    <%= f.label :ha_4_vancouver_island %><br>
    <%= f.text_field :ha_4_vancouver_island %>    
  </p>
  <p>
    <%= f.label :ha_5_northern %><br>
    <%= f.text_field :ha_5_northern %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/health_regions/edit.html.erb
<h1>Editing Health Region</h1>

<%= render 'form', health_region: @health_region %>

<%= link_to 'Show', @health_region %> |
<%= link_to 'Back', health_regions_path %>

app/views/health_regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Health Regions</h1>

<br>

<%= link_to 'Export CSV', health_regions_path(format: :csv) %>

<br>
<br>

<%= form_tag('/import_data_api', method: :get) do %>
  <input type="number" name="limit" min="1" placeholder="Enter import data limit" required>
  <%= submit_tag 'Import Data via API' %>
<% end %>

<table>
  <tr>
    <th>Dimension</th>
    <th>British Columbia</th>
    <th>HA Total</th>
    <th>HA 1 Interior</th>
    <th>HA 2 Fraser</th>
    <th>HA 3 Vancouver Coastal</th>
    <th>HA 4 Vancouver Island</th>
    <th>HA 5 Northern</th>
    <th>Actions</th>
  </tr>
  <% @health_regions.each do |health_region| %>
    <tr>
      <td><%= health_region.dimension %></td>
      <td><%= health_region.british_columbia %></td>
      <td><%= health_region.ha_total %></td>
      <td><%= health_region.ha_1_interior %></td>
      <td><%= health_region.ha_2_fraser %></td>
      <td><%= health_region.ha_3_vancouver_coastal %></td>
      <td><%= health_region.ha_4_vancouver_island %></td>
      <td><%= health_region.ha_5_northern %></td>
      <td>
        <%= link_to 'Show', health_region %>
        <%= link_to 'Edit', edit_health_region_path(health_region) %>
        <%= link_to 'Destroy', health_region, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/health_regions/new.html.erb
<h1>New Health Region</h1>

<%= render 'form', health_region: @health_region %>

<%= link_to 'Back', health_regions_path %>

app/views/health_regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dimension:</strong>
  <%= @health_region.dimension %>
</p>
<p>
  <strong>British Columbia:</strong>
  <%= @health_region.british_columbia %>
</p>
<p>
  <strong>HA Total:</strong>
  <%= @health_region.ha_total %>
</p>
<p>
  <strong>HA 1 Interior:</strong>
  <%= @health_region.ha_1_interior %>
</p>
<p>
  <strong>HA 2 Fraser:</strong>
  <%= @health_region.ha_2_fraser %>
</p>
<p>
  <strong>HA 3 Vancouver Coastal:</strong>
  <%= @health_region.ha_3_vancouver_coastal %>
</p>
<p>
  <strong>HA 4 Vancouver Island:</strong>
  <%= @health_region.ha_4_vancouver_island %>
</p>
<p>
  <strong>HA 5 Northern:</strong>
  <%= @health_region.ha_5_northern %>
</p>


<%= link_to 'Edit', edit_health_region_path(@health_region) %> |
<%= link_to 'Back', health_regions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>